export * from "./model.ts";
export { FigmaClient, RateLimitError, type FigmaClientOptions } from "./figma/client.ts";
export type * as Figma from "./figma/types.ts";
export { normalizeTree, normalizeNode, propName, type NormalizeContext } from "./figma/normalize.ts";
export { extractLibrary, parseVariantName, type PageEntry } from "./figma/library.ts";
export { roundTrip, type RoundTripReport } from "./figma/roundtrip.ts";
export * from "./code-model.ts";
export { readDtcg, flatName, parseColor, parseDimension, type DtcgDocument, type DtcgOptions, type DtcgResult, type RawToken } from "./tokens/dtcg.ts";
export * from "./adapter/protocol.ts";
export { AdapterHost, AdapterError } from "./adapter/host.ts";
export { serve, type Handlers } from "./adapter/serve.ts";
export { indexCoverage, tokenCoverage, type IndexCoverage, type TokenCoverage } from "./coverage.ts";
export { FEATURES, features, prepareCode, type Features, type FeatureName, type PairEvidence, type PropPair } from "./match/features.ts";
export { PRIOR_MODEL, fit, fitLogistic, score, type ScoringModel } from "./match/model.ts";
export { createMatcher, decide, matchLibrary, fitCalibration, calibratedProbability, nodeOwners, type Calibration, type Candidate, type MatchOptions, type MatchResult, type Tier } from "./match/match.ts";
export { evaluate, labelled, MIN_LABELS_FOR_CALIBRATION, type Evaluation, type EvaluateOptions, type LabelledDef } from "./match/evaluate.ts";
export { tokens as nameTokens, normValue, valueOverlap, tokenOverlap, jaroWinkler, commonPrefix } from "./match/text.ts";
export * from "./verify/types.ts";
export { verify, visibleText, type Check, type CheckStatus, type VerifyInput, type VerifyReport } from "./verify/verify.ts";
export { compareIndexes, signature, type DriftFinding, type DriftKind, type DriftOptions, type DriftReport, type DriftSeverity } from "./drift/drift.ts";
export { LlmError, type Llm, type LlmImage, type LlmRequest, type LlmResponse } from "./generate/llm.ts";
export { DEFAULT_OPENAI_MODEL, OpenAiLlm, type OpenAiOptions } from "./generate/openai.ts";
export { buildBrief, type Brief, type BriefInput, type Conventions, type InstanceHint } from "./generate/brief.ts";
export { tokenHints, type TokenHint } from "./generate/tokens-hint.ts";
export { generate, type Attempt, type GeneratedFile, type GenerateOptions, type GenerationEvent, type GenerationResult } from "./generate/generate.ts";
export { ScriptedLlm } from "./generate/scripted.ts";
